site_name: CoshUI
site_url: https://terrarizer03.github.io/coshui-docs
site_description: A Declarative UI Library for Python
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - content.tooltips
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.sections
  font: 
    text: Roboto
    code: JetBrains Mono
  logo: assets/images/coshui_logo_dark.png
  favicon: assets/images/coshui.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark Mode
      primary: black
      accent: deep purple
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light Mode
      primary: blue grey
      accent: deep purple

repo_url: https://gitlab.com/jylefv/CoshUI
repo_name: jylefv/CoshUI

plugins:
  - search
  - macros

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Introduction:
    - Installation: introduction/installation.md
    - Your First UI: introduction/your-first-ui.md
  - Learn the API:
    - Getting Started: learn-the-api/getting-started.md
    - Layout:
      - Overview: learn-the-api/layout/index.md
      - Width and Height: learn-the-api/layout/width-and-height.md
      - Padding and Margin: learn-the-api/layout/padding-and-margin.md
      - Position (x and y): learn-the-api/layout/position.md
      - Positioning: learn-the-api/layout/absolute-vs-relative.md
      - Align and Justify: learn-the-api/layout/align-and-justify.md
    - Styling:
      - Overview: learn-the-api/styling/index.md
      - Colors and Alpha: learn-the-api/styling/colors-and-alpha.md
      - Borders: learn-the-api/styling/borders.md
      - Border Radius: learn-the-api/styling/border-radius.md
      - Transforms: learn-the-api/styling/transforms.md
      - Classes: learn-the-api/styling/classes.md
    - Themes:
      - Overview: learn-the-api/themes/index.md
      - Default Themes: learn-the-api/themes/defaults.md
      - Theme Creation: learn-the-api/themes/create-theme.md
      - Set Theme: learn-the-api/themes/set-theme.md
    - Nodes:
      - Overview: learn-the-api/nodes/index.md
      - Parent Nodes:
        - Overview: learn-the-api/nodes/parent-nodes/index.md
        - Containers: learn-the-api/nodes/parent-nodes/containers.md
        - Grid: learn-the-api/nodes/parent-nodes/grid.md
        - Modal: learn-the-api/nodes/parent-nodes/modal.md
      - Widget Nodes:
        - Overview: learn-the-api/nodes/widgets/index.md
        - Button: learn-the-api/nodes/widgets/button.md
        - Label: learn-the-api/nodes/widgets/label.md
        - Input Field: learn-the-api/nodes/widgets/input-field.md
        - Checkbox: learn-the-api/nodes/widgets/checkbox.md
        - Dropdown: learn-the-api/nodes/widgets/dropdown.md
        - Images: learn-the-api/nodes/widgets/images.md
        - Slider: learn-the-api/nodes/widgets/slider.md
    - Animations:
      - Overview: learn-the-api/animations/index.md
      - Animate Function: learn-the-api/animations/animate-function.md
      - Properties: learn-the-api/animations/properties.md
      - Easing: learn-the-api/animations/easing.md
    - Interactions:
      - Overview: learn-the-api/interactions/index.md
      - Signals: learn-the-api/interactions/signals.md
      - Data Binding: learn-the-api/interactions/data-binding.md
      - Mouse Filter: learn-the-api/interactions/mouse-filter.md
    - Text System:
      - Overview: learn-the-api/text/index.md
      - Text Properties: learn-the-api/text/text-properties.md
      - Set Default Font: learn-the-api/text/set-default.md
    - Types and Enums:
      - Overview: learn-the-api/types/index.md
      - Layout Enums: learn-the-api/types/layout-enums.md
      - Interaction Enums: learn-the-api/types/interaction-enums.md
      - Text Enums: learn-the-api/types/text-enums.md
    - Backends:
      - Overview: learn-the-api/backends/index.md
      - Pygame: learn-the-api/backends/pygame.md
      - Raylib: learn-the-api/backends/raylib.md
      - PyOpenGL: learn-the-api/backends/pyopengl.md
    - All Node Properties:
      - Overview: learn-the-api/properties/index.md
      - x: learn-the-api/properties/x.md
      - y: learn-the-api/properties/y.md
      - style: learn-the-api/properties/style.md
      - width: learn-the-api/properties/width.md
      - height: learn-the-api/properties/height.md
      - gap: learn-the-api/properties/gap.md
      - padding: learn-the-api/properties/padding.md
      - margin: learn-the-api/properties/margin.md
      - direction: learn-the-api/properties/direction.md
      - justify: learn-the-api/properties/justify.md
      - align: learn-the-api/properties/align.md
      - overflow: learn-the-api/properties/overflow.md
      - positioning: learn-the-api/properties/positioning.md
      - z_index: learn-the-api/properties/z-index.md
      - id: learn-the-api/properties/id.md
      - classes: learn-the-api/properties/classes.md
      - mouse_filter: learn-the-api/properties/mouse-filter.md
      - background_color: learn-the-api/properties/background-color.md
      - alpha: learn-the-api/properties/alpha.md
      - border: learn-the-api/properties/border.md
      - border_radius: learn-the-api/properties/border-radius.md
      - transform_position: learn-the-api/properties/transform-position.md
      - transform_scale: learn-the-api/properties/transform-scale.md
      - transform_rotation: learn-the-api/properties/transform-rotation.md
      - text: learn-the-api/properties/text.md
      - font: learn-the-api/properties/font.md
      - font_size: learn-the-api/properties/font-size.md
      - text_color: learn-the-api/properties/text-color.md
      - text_align: learn-the-api/properties/text-align.md
      - text_justify: learn-the-api/properties/text-justify.md
      - text_overflow: learn-the-api/properties/text-overflow.md
      - src: learn-the-api/properties/image-src.md
      - checked: learn-the-api/properties/checked.md
      - checked_color: learn-the-api/properties/checked-color.md
      - unchecked_color: learn-the-api/properties/unchecked-color.md
    - All Public Functions:
      - Overview: learn-the-api/utility/index.md
      - add_class: learn-the-api/utility/add-class.md
      - get_signal: learn-the-api/utility/get-signal.md
      - animate: learn-the-api/utility/animate.md
      - add_font: learn-the-api/utility/add-font.md
      - set_default_font: learn-the-api/utility/set-default-font.md
      - create_theme: learn-the-api/utility/create-theme.md
      - set_default_theme: learn-the-api/utility/set-default-theme.md
  - Examples:
    - Health Bar: examples/health-bar.md
  - Changelog: changelog.md

extra:
  version: 0.2.4
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JyleFV/CoshUI
      name: GitHub Repository (Mirror)
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/jylefv/CoshUI
      name: GitLab Repository (Primary)
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/wZUqKv9ux
      name: Join the Discord

copyright: Copyright &copy; 2026 JyleFV